import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";

// Load .env file if present
function loadEnv() {
	const envPath = path.resolve('.env');
	if (fs.existsSync(envPath)) {
		try {
			const content = fs.readFileSync(envPath, 'utf8');
			for (const line of content.split(/\r?\n/)) {
				const trimmed = line.trim();
				if (!trimmed || trimmed.startsWith('#')) continue;
				const eqIdx = trimmed.indexOf('=');
				if (eqIdx !== -1) {
					const key = trimmed.slice(0, eqIdx).trim();
					let val = trimmed.slice(eqIdx + 1).trim();
					if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
						val = val.slice(1, -1);
					}
					if (key && !(key in process.env)) {
						process.env[key] = val;
					}
				}
			}
		} catch {
			// ignore
		}
	}
}
loadEnv();

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

function copyToVaults() {
	const userProfile = process.env.USERPROFILE || '';
	const customVault = process.env.OBSIDIAN_VAULT_PATH;
	const candidateVaults = [
		...(customVault ? [customVault] : []),
		path.join(userProfile, 'OneDrive', 'PlugVaults', '.obsidian', 'plugins', 'assistant-emily'),
		path.join(userProfile, 'OneDrive', 'PlugVaults', '.obsidian', 'plugins', 'obsidian-assistant-emily'),
		path.join(userProfile, 'OneDrive', 'ObsidianVaults', '.obsidian', 'plugins', 'assistant-emily'),
		path.join(userProfile, 'OneDrive', 'ObsidianVaults', '.obsidian', 'plugins', 'obsidian-assistant-emily'),
		path.join(userProfile, 'PlugVaults', '.obsidian', 'plugins', 'assistant-emily'),
		path.join(userProfile, 'PlugVaults', '.obsidian', 'plugins', 'obsidian-assistant-emily')
	];

	for (const destDir of candidateVaults) {
		if (fs.existsSync(destDir)) {
			try {
				fs.copyFileSync('main.js', path.join(destDir, 'main.js'));
				if (fs.existsSync('manifest.json')) {
					fs.copyFileSync('manifest.json', path.join(destDir, 'manifest.json'));
				}
				if (fs.existsSync('styles.css')) {
					fs.copyFileSync('styles.css', path.join(destDir, 'styles.css'));
				}
				console.log(`[Deploy] Successfully synced bundle to: ${destDir}`);
			} catch (err) {
				console.error(`[Deploy Error] Failed to sync to ${destDir}:`, err);
			}
		}
	}
}

if (prod) {
	await context.rebuild();
	copyToVaults();
	process.exit(0);
} else {
	await context.watch();
}
