import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

function copyToVaults() {
	const userProfile = process.env.USERPROFILE || '';
	const customVault = process.env.OBSIDIAN_VAULT_PATH;
	const candidateVaults = [
		...(customVault ? [customVault] : []),
		path.join(userProfile, 'OneDrive', 'PlugVaults', '.obsidian', 'plugins', 'obsidian-assistant-emily'),
		path.join(userProfile, 'OneDrive', 'ObsidianVaults', '.obsidian', 'plugins', 'obsidian-assistant-emily'),
		path.join(userProfile, 'PlugVaults', '.obsidian', 'plugins', 'obsidian-assistant-emily')
	];

	for (const destDir of candidateVaults) {
		if (fs.existsSync(destDir)) {
			try {
				fs.copyFileSync('main.js', path.join(destDir, 'main.js'));
				if (fs.existsSync('manifest.json')) {
					fs.copyFileSync('manifest.json', path.join(destDir, 'manifest.json'));
				}
				if (fs.existsSync('styles.css')) {
					fs.copyFileSync('styles.css', path.join(destDir, 'styles.css'));
				}
				console.log(`[Deploy] Successfully synced bundle to: ${destDir}`);
			} catch (err) {
				console.error(`[Deploy Error] Failed to sync to ${destDir}:`, err);
			}
		}
	}
}

if (prod) {
	await context.rebuild();
	copyToVaults();
	process.exit(0);
} else {
	await context.watch();
}
